// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: platform/v1/platform.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialStatus int32

const (
	CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED        CredentialStatus = 0
	CredentialStatus_CREDENTIAL_STATUS_ACTIVE             CredentialStatus = 1
	CredentialStatus_CREDENTIAL_STATUS_EXPIRED            CredentialStatus = 2
	CredentialStatus_CREDENTIAL_STATUS_INVALID            CredentialStatus = 3
	CredentialStatus_CREDENTIAL_STATUS_CHALLENGE_REQUIRED CredentialStatus = 4
)

// Enum value maps for CredentialStatus.
var (
	CredentialStatus_name = map[int32]string{
		0: "CREDENTIAL_STATUS_UNSPECIFIED",
		1: "CREDENTIAL_STATUS_ACTIVE",
		2: "CREDENTIAL_STATUS_EXPIRED",
		3: "CREDENTIAL_STATUS_INVALID",
		4: "CREDENTIAL_STATUS_CHALLENGE_REQUIRED",
	}
	CredentialStatus_value = map[string]int32{
		"CREDENTIAL_STATUS_UNSPECIFIED":        0,
		"CREDENTIAL_STATUS_ACTIVE":             1,
		"CREDENTIAL_STATUS_EXPIRED":            2,
		"CREDENTIAL_STATUS_INVALID":            3,
		"CREDENTIAL_STATUS_CHALLENGE_REQUIRED": 4,
	}
)

func (x CredentialStatus) Enum() *CredentialStatus {
	p := new(CredentialStatus)
	*p = x
	return p
}

func (x CredentialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_platform_proto_enumTypes[0].Descriptor()
}

func (CredentialStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_platform_proto_enumTypes[0]
}

func (x CredentialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialStatus.Descriptor instead.
func (CredentialStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

type DescribePlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribePlatformRequest) Reset() {
	*x = DescribePlatformRequest{}
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribePlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePlatformRequest) ProtoMessage() {}

func (x *DescribePlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePlatformRequest.ProtoReflect.Descriptor instead.
func (*DescribePlatformRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

type DescribePlatformResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlatformKey      string                 `protobuf:"bytes,1,opt,name=platform_key,json=platformKey,proto3" json:"platform_key,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ServiceAudience  string                 `protobuf:"bytes,3,opt,name=service_audience,json=serviceAudience,proto3" json:"service_audience,omitempty"`
	SupportedActions []string               `protobuf:"bytes,4,rep,name=supported_actions,json=supportedActions,proto3" json:"supported_actions,omitempty"`
	CredentialSchema *structpb.Struct       `protobuf:"bytes,5,opt,name=credential_schema,json=credentialSchema,proto3" json:"credential_schema,omitempty"`
	Version          string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DescribePlatformResponse) Reset() {
	*x = DescribePlatformResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribePlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePlatformResponse) ProtoMessage() {}

func (x *DescribePlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePlatformResponse.ProtoReflect.Descriptor instead.
func (*DescribePlatformResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *DescribePlatformResponse) GetPlatformKey() string {
	if x != nil {
		return x.PlatformKey
	}
	return ""
}

func (x *DescribePlatformResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DescribePlatformResponse) GetServiceAudience() string {
	if x != nil {
		return x.ServiceAudience
	}
	return ""
}

func (x *DescribePlatformResponse) GetSupportedActions() []string {
	if x != nil {
		return x.SupportedActions
	}
	return nil
}

func (x *DescribePlatformResponse) GetCredentialSchema() *structpb.Struct {
	if x != nil {
		return x.CredentialSchema
	}
	return nil
}

func (x *DescribePlatformResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DeviceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceFp      string                 `protobuf:"bytes,2,opt,name=device_fp,json=deviceFp,proto3" json:"device_fp,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSummary) Reset() {
	*x = DeviceSummary{}
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSummary) ProtoMessage() {}

func (x *DeviceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSummary.ProtoReflect.Descriptor instead.
func (*DeviceSummary) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceSummary) GetDeviceFp() string {
	if x != nil {
		return x.DeviceFp
	}
	return ""
}

func (x *DeviceSummary) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceSummary) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *DeviceSummary) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ProfileSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	GameBiz           string                 `protobuf:"bytes,3,opt,name=game_biz,json=gameBiz,proto3" json:"game_biz,omitempty"`
	Region            string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	PlayerId          string                 `protobuf:"bytes,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname          string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level             int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	IsDefault         bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileSummary) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileSummary) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *ProfileSummary) GetGameBiz() string {
	if x != nil {
		return x.GameBiz
	}
	return ""
}

func (x *ProfileSummary) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProfileSummary) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ProfileSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfileSummary) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type GetCredentialSummaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialSummaryRequest) Reset() {
	*x = GetCredentialSummaryRequest{}
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryRequest) ProtoMessage() {}

func (x *GetCredentialSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *GetCredentialSummaryRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetCredentialSummaryRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type GetCredentialSummaryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlatformAccountId string                 `protobuf:"bytes,1,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	Status            CredentialStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=paigram.platform.v1.CredentialStatus" json:"status,omitempty"`
	LastValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	LastRefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_refreshed_at,json=lastRefreshedAt,proto3" json:"last_refreshed_at,omitempty"`
	Devices           []*DeviceSummary       `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	Profiles          []*ProfileSummary      `protobuf:"bytes,6,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialSummaryResponse) Reset() {
	*x = GetCredentialSummaryResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryResponse) ProtoMessage() {}

func (x *GetCredentialSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{5}
}

func (x *GetCredentialSummaryResponse) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *GetCredentialSummaryResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *GetCredentialSummaryResponse) GetLastValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastValidatedAt
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetLastRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshedAt
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetDevices() []*DeviceSummary {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_platform_v1_platform_proto protoreflect.FileDescriptor

const file_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\x1aplatform/v1/platform.proto\x12\x13paigram.platform.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n" +
	"\x17DescribePlatformRequest\"\x98\x02\n" +
	"\x18DescribePlatformResponse\x12!\n" +
	"\fplatform_key\x18\x01 \x01(\tR\vplatformKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12)\n" +
	"\x10service_audience\x18\x03 \x01(\tR\x0fserviceAudience\x12+\n" +
	"\x11supported_actions\x18\x04 \x03(\tR\x10supportedActions\x12D\n" +
	"\x11credential_schema\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x10credentialSchema\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xc3\x01\n" +
	"\rDeviceSummary\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tdevice_fp\x18\x02 \x01(\tR\bdeviceFp\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xf1\x01\n" +
	"\x0eProfileSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12\x19\n" +
	"\bgame_biz\x18\x03 \x01(\tR\agameBiz\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\"t\n" +
	"\x1bGetCredentialSummaryRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"\x9c\x03\n" +
	"\x1cGetCredentialSummaryResponse\x12.\n" +
	"\x13platform_account_id\x18\x01 \x01(\tR\x11platformAccountId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.paigram.platform.v1.CredentialStatusR\x06status\x12F\n" +
	"\x11last_validated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastValidatedAt\x12F\n" +
	"\x11last_refreshed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRefreshedAt\x12<\n" +
	"\adevices\x18\x05 \x03(\v2\".paigram.platform.v1.DeviceSummaryR\adevices\x12?\n" +
	"\bprofiles\x18\x06 \x03(\v2#.paigram.platform.v1.ProfileSummaryR\bprofiles*\xbb\x01\n" +
	"\x10CredentialStatus\x12!\n" +
	"\x1dCREDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_EXPIRED\x10\x02\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_INVALID\x10\x03\x12(\n" +
	"$CREDENTIAL_STATUS_CHALLENGE_REQUIRED\x10\x042\xff\x01\n" +
	"\x0fPlatformService\x12o\n" +
	"\x10DescribePlatform\x12,.paigram.platform.v1.DescribePlatformRequest\x1a-.paigram.platform.v1.DescribePlatformResponse\x12{\n" +
	"\x14GetCredentialSummary\x120.paigram.platform.v1.GetCredentialSummaryRequest\x1a1.paigram.platform.v1.GetCredentialSummaryResponseB?Z=github.com/PaiGramTeam/proto-contracts/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_platform_proto_rawDescOnce sync.Once
	file_platform_v1_platform_proto_rawDescData []byte
)

func file_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)))
	})
	return file_platform_v1_platform_proto_rawDescData
}

var file_platform_v1_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_platform_v1_platform_proto_goTypes = []any{
	(CredentialStatus)(0),                // 0: paigram.platform.v1.CredentialStatus
	(*DescribePlatformRequest)(nil),      // 1: paigram.platform.v1.DescribePlatformRequest
	(*DescribePlatformResponse)(nil),     // 2: paigram.platform.v1.DescribePlatformResponse
	(*DeviceSummary)(nil),                // 3: paigram.platform.v1.DeviceSummary
	(*ProfileSummary)(nil),               // 4: paigram.platform.v1.ProfileSummary
	(*GetCredentialSummaryRequest)(nil),  // 5: paigram.platform.v1.GetCredentialSummaryRequest
	(*GetCredentialSummaryResponse)(nil), // 6: paigram.platform.v1.GetCredentialSummaryResponse
	(*structpb.Struct)(nil),              // 7: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_platform_v1_platform_proto_depIdxs = []int32{
	7, // 0: paigram.platform.v1.DescribePlatformResponse.credential_schema:type_name -> google.protobuf.Struct
	8, // 1: paigram.platform.v1.DeviceSummary.last_seen_at:type_name -> google.protobuf.Timestamp
	0, // 2: paigram.platform.v1.GetCredentialSummaryResponse.status:type_name -> paigram.platform.v1.CredentialStatus
	8, // 3: paigram.platform.v1.GetCredentialSummaryResponse.last_validated_at:type_name -> google.protobuf.Timestamp
	8, // 4: paigram.platform.v1.GetCredentialSummaryResponse.last_refreshed_at:type_name -> google.protobuf.Timestamp
	3, // 5: paigram.platform.v1.GetCredentialSummaryResponse.devices:type_name -> paigram.platform.v1.DeviceSummary
	4, // 6: paigram.platform.v1.GetCredentialSummaryResponse.profiles:type_name -> paigram.platform.v1.ProfileSummary
	1, // 7: paigram.platform.v1.PlatformService.DescribePlatform:input_type -> paigram.platform.v1.DescribePlatformRequest
	5, // 8: paigram.platform.v1.PlatformService.GetCredentialSummary:input_type -> paigram.platform.v1.GetCredentialSummaryRequest
	2, // 9: paigram.platform.v1.PlatformService.DescribePlatform:output_type -> paigram.platform.v1.DescribePlatformResponse
	6, // 10: paigram.platform.v1.PlatformService.GetCredentialSummary:output_type -> paigram.platform.v1.GetCredentialSummaryResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_platform_v1_platform_proto_init() }
func file_platform_v1_platform_proto_init() {
	if File_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_platform_v1_platform_proto_depIdxs,
		EnumInfos:         file_platform_v1_platform_proto_enumTypes,
		MessageInfos:      file_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_platform_v1_platform_proto = out.File
	file_platform_v1_platform_proto_goTypes = nil
	file_platform_v1_platform_proto_depIdxs = nil
}
