// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: platform/v1/platform.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_DescribePlatform_FullMethodName        = "/paigram.platform.v1.PlatformService/DescribePlatform"
	PlatformService_GetCredentialSummary_FullMethodName    = "/paigram.platform.v1.PlatformService/GetCredentialSummary"
	PlatformService_PutCredential_FullMethodName           = "/paigram.platform.v1.PlatformService/PutCredential"
	PlatformService_RefreshCredential_FullMethodName       = "/paigram.platform.v1.PlatformService/RefreshCredential"
	PlatformService_DeleteCredential_FullMethodName        = "/paigram.platform.v1.PlatformService/DeleteCredential"
	PlatformService_InvalidateConsumerGrant_FullMethodName = "/paigram.platform.v1.PlatformService/InvalidateConsumerGrant"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformServiceClient interface {
	DescribePlatform(ctx context.Context, in *DescribePlatformRequest, opts ...grpc.CallOption) (*DescribePlatformResponse, error)
	GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error)
	PutCredential(ctx context.Context, in *PutCredentialRequest, opts ...grpc.CallOption) (*PutCredentialResponse, error)
	RefreshCredential(ctx context.Context, in *RefreshCredentialRequest, opts ...grpc.CallOption) (*RefreshCredentialResponse, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
	InvalidateConsumerGrant(ctx context.Context, in *InvalidateConsumerGrantRequest, opts ...grpc.CallOption) (*InvalidateConsumerGrantResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) DescribePlatform(ctx context.Context, in *DescribePlatformRequest, opts ...grpc.CallOption) (*DescribePlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribePlatformResponse)
	err := c.cc.Invoke(ctx, PlatformService_DescribePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialSummaryResponse)
	err := c.cc.Invoke(ctx, PlatformService_GetCredentialSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) PutCredential(ctx context.Context, in *PutCredentialRequest, opts ...grpc.CallOption) (*PutCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutCredentialResponse)
	err := c.cc.Invoke(ctx, PlatformService_PutCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) RefreshCredential(ctx context.Context, in *RefreshCredentialRequest, opts ...grpc.CallOption) (*RefreshCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshCredentialResponse)
	err := c.cc.Invoke(ctx, PlatformService_RefreshCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, PlatformService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) InvalidateConsumerGrant(ctx context.Context, in *InvalidateConsumerGrantRequest, opts ...grpc.CallOption) (*InvalidateConsumerGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateConsumerGrantResponse)
	err := c.cc.Invoke(ctx, PlatformService_InvalidateConsumerGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
type PlatformServiceServer interface {
	DescribePlatform(context.Context, *DescribePlatformRequest) (*DescribePlatformResponse, error)
	GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error)
	PutCredential(context.Context, *PutCredentialRequest) (*PutCredentialResponse, error)
	RefreshCredential(context.Context, *RefreshCredentialRequest) (*RefreshCredentialResponse, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	InvalidateConsumerGrant(context.Context, *InvalidateConsumerGrantRequest) (*InvalidateConsumerGrantResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) DescribePlatform(context.Context, *DescribePlatformRequest) (*DescribePlatformResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribePlatform not implemented")
}
func (UnimplementedPlatformServiceServer) GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialSummary not implemented")
}
func (UnimplementedPlatformServiceServer) PutCredential(context.Context, *PutCredentialRequest) (*PutCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCredential not implemented")
}
func (UnimplementedPlatformServiceServer) RefreshCredential(context.Context, *RefreshCredentialRequest) (*RefreshCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshCredential not implemented")
}
func (UnimplementedPlatformServiceServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedPlatformServiceServer) InvalidateConsumerGrant(context.Context, *InvalidateConsumerGrantRequest) (*InvalidateConsumerGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidateConsumerGrant not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call panics, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_DescribePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DescribePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DescribePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DescribePlatform(ctx, req.(*DescribePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetCredentialSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetCredentialSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetCredentialSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetCredentialSummary(ctx, req.(*GetCredentialSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_PutCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).PutCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_PutCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).PutCredential(ctx, req.(*PutCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_RefreshCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).RefreshCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_RefreshCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).RefreshCredential(ctx, req.(*RefreshCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_InvalidateConsumerGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateConsumerGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).InvalidateConsumerGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_InvalidateConsumerGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).InvalidateConsumerGrant(ctx, req.(*InvalidateConsumerGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paigram.platform.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribePlatform",
			Handler:    _PlatformService_DescribePlatform_Handler,
		},
		{
			MethodName: "GetCredentialSummary",
			Handler:    _PlatformService_GetCredentialSummary_Handler,
		},
		{
			MethodName: "PutCredential",
			Handler:    _PlatformService_PutCredential_Handler,
		},
		{
			MethodName: "RefreshCredential",
			Handler:    _PlatformService_RefreshCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _PlatformService_DeleteCredential_Handler,
		},
		{
			MethodName: "InvalidateConsumerGrant",
			Handler:    _PlatformService_InvalidateConsumerGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/v1/platform.proto",
}
