// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: mihomo/v1/credential.proto

package mihomov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialStatus int32

const (
	CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED        CredentialStatus = 0
	CredentialStatus_CREDENTIAL_STATUS_ACTIVE             CredentialStatus = 1
	CredentialStatus_CREDENTIAL_STATUS_EXPIRED            CredentialStatus = 2
	CredentialStatus_CREDENTIAL_STATUS_INVALID            CredentialStatus = 3
	CredentialStatus_CREDENTIAL_STATUS_CHALLENGE_REQUIRED CredentialStatus = 4
)

// Enum value maps for CredentialStatus.
var (
	CredentialStatus_name = map[int32]string{
		0: "CREDENTIAL_STATUS_UNSPECIFIED",
		1: "CREDENTIAL_STATUS_ACTIVE",
		2: "CREDENTIAL_STATUS_EXPIRED",
		3: "CREDENTIAL_STATUS_INVALID",
		4: "CREDENTIAL_STATUS_CHALLENGE_REQUIRED",
	}
	CredentialStatus_value = map[string]int32{
		"CREDENTIAL_STATUS_UNSPECIFIED":        0,
		"CREDENTIAL_STATUS_ACTIVE":             1,
		"CREDENTIAL_STATUS_EXPIRED":            2,
		"CREDENTIAL_STATUS_INVALID":            3,
		"CREDENTIAL_STATUS_CHALLENGE_REQUIRED": 4,
	}
)

func (x CredentialStatus) Enum() *CredentialStatus {
	p := new(CredentialStatus)
	*p = x
	return p
}

func (x CredentialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mihomo_v1_credential_proto_enumTypes[0].Descriptor()
}

func (CredentialStatus) Type() protoreflect.EnumType {
	return &file_mihomo_v1_credential_proto_enumTypes[0]
}

func (x CredentialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialStatus.Descriptor instead.
func (CredentialStatus) EnumDescriptor() ([]byte, []int) {
	return file_mihomo_v1_credential_proto_rawDescGZIP(), []int{0}
}

type DeviceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceFp      string                 `protobuf:"bytes,2,opt,name=device_fp,json=deviceFp,proto3" json:"device_fp,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSummary) Reset() {
	*x = DeviceSummary{}
	mi := &file_mihomo_v1_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSummary) ProtoMessage() {}

func (x *DeviceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mihomo_v1_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSummary.ProtoReflect.Descriptor instead.
func (*DeviceSummary) Descriptor() ([]byte, []int) {
	return file_mihomo_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceSummary) GetDeviceFp() string {
	if x != nil {
		return x.DeviceFp
	}
	return ""
}

func (x *DeviceSummary) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceSummary) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *DeviceSummary) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ProfileSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	GameBiz           string                 `protobuf:"bytes,3,opt,name=game_biz,json=gameBiz,proto3" json:"game_biz,omitempty"`
	Region            string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	PlayerId          string                 `protobuf:"bytes,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname          string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level             int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	IsDefault         bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_mihomo_v1_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mihomo_v1_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_mihomo_v1_credential_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileSummary) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileSummary) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *ProfileSummary) GetGameBiz() string {
	if x != nil {
		return x.GameBiz
	}
	return ""
}

func (x *ProfileSummary) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProfileSummary) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ProfileSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfileSummary) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type GetCredentialSummaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialSummaryRequest) Reset() {
	*x = GetCredentialSummaryRequest{}
	mi := &file_mihomo_v1_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryRequest) ProtoMessage() {}

func (x *GetCredentialSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mihomo_v1_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryRequest) Descriptor() ([]byte, []int) {
	return file_mihomo_v1_credential_proto_rawDescGZIP(), []int{2}
}

func (x *GetCredentialSummaryRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetCredentialSummaryRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type GetCredentialSummaryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlatformAccountId string                 `protobuf:"bytes,1,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	Status            CredentialStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=paigram.mihomo.v1.CredentialStatus" json:"status,omitempty"`
	LastValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	LastRefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_refreshed_at,json=lastRefreshedAt,proto3" json:"last_refreshed_at,omitempty"`
	Devices           []*DeviceSummary       `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	Profiles          []*ProfileSummary      `protobuf:"bytes,6,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialSummaryResponse) Reset() {
	*x = GetCredentialSummaryResponse{}
	mi := &file_mihomo_v1_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryResponse) ProtoMessage() {}

func (x *GetCredentialSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mihomo_v1_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryResponse) Descriptor() ([]byte, []int) {
	return file_mihomo_v1_credential_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialSummaryResponse) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *GetCredentialSummaryResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *GetCredentialSummaryResponse) GetLastValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastValidatedAt
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetLastRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshedAt
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetDevices() []*DeviceSummary {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetCredentialSummaryResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_mihomo_v1_credential_proto protoreflect.FileDescriptor

const file_mihomo_v1_credential_proto_rawDesc = "" +
	"\n" +
	"\x1amihomo/v1/credential.proto\x12\x11paigram.mihomo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\rDeviceSummary\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tdevice_fp\x18\x02 \x01(\tR\bdeviceFp\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xf1\x01\n" +
	"\x0eProfileSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12\x19\n" +
	"\bgame_biz\x18\x03 \x01(\tR\agameBiz\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\"t\n" +
	"\x1bGetCredentialSummaryRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"\x96\x03\n" +
	"\x1cGetCredentialSummaryResponse\x12.\n" +
	"\x13platform_account_id\x18\x01 \x01(\tR\x11platformAccountId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.paigram.mihomo.v1.CredentialStatusR\x06status\x12F\n" +
	"\x11last_validated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastValidatedAt\x12F\n" +
	"\x11last_refreshed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRefreshedAt\x12:\n" +
	"\adevices\x18\x05 \x03(\v2 .paigram.mihomo.v1.DeviceSummaryR\adevices\x12=\n" +
	"\bprofiles\x18\x06 \x03(\v2!.paigram.mihomo.v1.ProfileSummaryR\bprofiles*\xbb\x01\n" +
	"\x10CredentialStatus\x12!\n" +
	"\x1dCREDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_EXPIRED\x10\x02\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_INVALID\x10\x03\x12(\n" +
	"$CREDENTIAL_STATUS_CHALLENGE_REQUIRED\x10\x042\x92\x01\n" +
	"\x17MihomoCredentialService\x12w\n" +
	"\x14GetCredentialSummary\x12..paigram.mihomo.v1.GetCredentialSummaryRequest\x1a/.paigram.mihomo.v1.GetCredentialSummaryResponseB;Z9github.com/PaiGramTeam/proto-contracts/mihomo/v1;mihomov1b\x06proto3"

var (
	file_mihomo_v1_credential_proto_rawDescOnce sync.Once
	file_mihomo_v1_credential_proto_rawDescData []byte
)

func file_mihomo_v1_credential_proto_rawDescGZIP() []byte {
	file_mihomo_v1_credential_proto_rawDescOnce.Do(func() {
		file_mihomo_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mihomo_v1_credential_proto_rawDesc), len(file_mihomo_v1_credential_proto_rawDesc)))
	})
	return file_mihomo_v1_credential_proto_rawDescData
}

var file_mihomo_v1_credential_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mihomo_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mihomo_v1_credential_proto_goTypes = []any{
	(CredentialStatus)(0),                // 0: paigram.mihomo.v1.CredentialStatus
	(*DeviceSummary)(nil),                // 1: paigram.mihomo.v1.DeviceSummary
	(*ProfileSummary)(nil),               // 2: paigram.mihomo.v1.ProfileSummary
	(*GetCredentialSummaryRequest)(nil),  // 3: paigram.mihomo.v1.GetCredentialSummaryRequest
	(*GetCredentialSummaryResponse)(nil), // 4: paigram.mihomo.v1.GetCredentialSummaryResponse
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_mihomo_v1_credential_proto_depIdxs = []int32{
	5, // 0: paigram.mihomo.v1.DeviceSummary.last_seen_at:type_name -> google.protobuf.Timestamp
	0, // 1: paigram.mihomo.v1.GetCredentialSummaryResponse.status:type_name -> paigram.mihomo.v1.CredentialStatus
	5, // 2: paigram.mihomo.v1.GetCredentialSummaryResponse.last_validated_at:type_name -> google.protobuf.Timestamp
	5, // 3: paigram.mihomo.v1.GetCredentialSummaryResponse.last_refreshed_at:type_name -> google.protobuf.Timestamp
	1, // 4: paigram.mihomo.v1.GetCredentialSummaryResponse.devices:type_name -> paigram.mihomo.v1.DeviceSummary
	2, // 5: paigram.mihomo.v1.GetCredentialSummaryResponse.profiles:type_name -> paigram.mihomo.v1.ProfileSummary
	3, // 6: paigram.mihomo.v1.MihomoCredentialService.GetCredentialSummary:input_type -> paigram.mihomo.v1.GetCredentialSummaryRequest
	4, // 7: paigram.mihomo.v1.MihomoCredentialService.GetCredentialSummary:output_type -> paigram.mihomo.v1.GetCredentialSummaryResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mihomo_v1_credential_proto_init() }
func file_mihomo_v1_credential_proto_init() {
	if File_mihomo_v1_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mihomo_v1_credential_proto_rawDesc), len(file_mihomo_v1_credential_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mihomo_v1_credential_proto_goTypes,
		DependencyIndexes: file_mihomo_v1_credential_proto_depIdxs,
		EnumInfos:         file_mihomo_v1_credential_proto_enumTypes,
		MessageInfos:      file_mihomo_v1_credential_proto_msgTypes,
	}.Build()
	File_mihomo_v1_credential_proto = out.File
	file_mihomo_v1_credential_proto_goTypes = nil
	file_mihomo_v1_credential_proto_depIdxs = nil
}
