// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: mihomo/v1/credential.proto

package mihomov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MihomoCredentialService_GetCredentialSummary_FullMethodName = "/paigram.mihomo.v1.MihomoCredentialService/GetCredentialSummary"
)

// MihomoCredentialServiceClient is the client API for MihomoCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MihomoCredentialServiceClient interface {
	GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error)
}

type mihomoCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMihomoCredentialServiceClient(cc grpc.ClientConnInterface) MihomoCredentialServiceClient {
	return &mihomoCredentialServiceClient{cc}
}

func (c *mihomoCredentialServiceClient) GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialSummaryResponse)
	err := c.cc.Invoke(ctx, MihomoCredentialService_GetCredentialSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MihomoCredentialServiceServer is the server API for MihomoCredentialService service.
// All implementations must embed UnimplementedMihomoCredentialServiceServer
// for forward compatibility.
type MihomoCredentialServiceServer interface {
	GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error)
	mustEmbedUnimplementedMihomoCredentialServiceServer()
}

// UnimplementedMihomoCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMihomoCredentialServiceServer struct{}

func (UnimplementedMihomoCredentialServiceServer) GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialSummary not implemented")
}
func (UnimplementedMihomoCredentialServiceServer) mustEmbedUnimplementedMihomoCredentialServiceServer() {
}
func (UnimplementedMihomoCredentialServiceServer) testEmbeddedByValue() {}

// UnsafeMihomoCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MihomoCredentialServiceServer will
// result in compilation errors.
type UnsafeMihomoCredentialServiceServer interface {
	mustEmbedUnimplementedMihomoCredentialServiceServer()
}

func RegisterMihomoCredentialServiceServer(s grpc.ServiceRegistrar, srv MihomoCredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedMihomoCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MihomoCredentialService_ServiceDesc, srv)
}

func _MihomoCredentialService_GetCredentialSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoCredentialServiceServer).GetCredentialSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoCredentialService_GetCredentialSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoCredentialServiceServer).GetCredentialSummary(ctx, req.(*GetCredentialSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MihomoCredentialService_ServiceDesc is the grpc.ServiceDesc for MihomoCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MihomoCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paigram.mihomo.v1.MihomoCredentialService",
	HandlerType: (*MihomoCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentialSummary",
			Handler:    _MihomoCredentialService_GetCredentialSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mihomo/v1/credential.proto",
}
