// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: template/v1/template.proto

package templatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderAndUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模板名（不含扩展名），形如 "genshin/sign_result"。
	TemplateName string `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	// JSON 序列化后的模板数据；bytes 形式是为了避免 dynamic message 复杂度（**非**媒体 bytes）。
	DataJson      []byte         `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Options       *RenderOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderAndUploadRequest) Reset() {
	*x = RenderAndUploadRequest{}
	mi := &file_template_v1_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderAndUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderAndUploadRequest) ProtoMessage() {}

func (x *RenderAndUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderAndUploadRequest.ProtoReflect.Descriptor instead.
func (*RenderAndUploadRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{0}
}

func (x *RenderAndUploadRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *RenderAndUploadRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *RenderAndUploadRequest) GetOptions() *RenderOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// RenderOptions 承载渲染参数。
// 注意：当前字段语义为 playwright-specific；future cross-renderer 实现需要扩展此 message
// 或新增一个 renderer-options oneof。
type RenderOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewportWidth int32                  `protobuf:"varint,1,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	// 0 表示自适应内容高度。
	ViewportHeight int32 `protobuf:"varint,2,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	// 默认 2.0。
	DeviceScaleFactor float32 `protobuf:"fixed32,3,opt,name=device_scale_factor,json=deviceScaleFactor,proto3" json:"device_scale_factor,omitempty"`
	// "png" 或 "jpeg"，默认 "png"。
	Format        string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderOptions) Reset() {
	*x = RenderOptions{}
	mi := &file_template_v1_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderOptions) ProtoMessage() {}

func (x *RenderOptions) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderOptions.ProtoReflect.Descriptor instead.
func (*RenderOptions) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{1}
}

func (x *RenderOptions) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *RenderOptions) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

func (x *RenderOptions) GetDeviceScaleFactor() float32 {
	if x != nil {
		return x.DeviceScaleFactor
	}
	return 0
}

func (x *RenderOptions) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type RenderAndUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// minio public URL。
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// bucket 内对象 key，用于后续清理或 audit。
	ObjectKey string `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	SizeBytes int64  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// 0 表示无过期。
	ExpiresAtUnix int64 `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderAndUploadResponse) Reset() {
	*x = RenderAndUploadResponse{}
	mi := &file_template_v1_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderAndUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderAndUploadResponse) ProtoMessage() {}

func (x *RenderAndUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderAndUploadResponse.ProtoReflect.Descriptor instead.
func (*RenderAndUploadResponse) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{2}
}

func (x *RenderAndUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RenderAndUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *RenderAndUploadResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RenderAndUploadResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type DescribeServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeServiceRequest) Reset() {
	*x = DescribeServiceRequest{}
	mi := &file_template_v1_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceRequest) ProtoMessage() {}

func (x *DescribeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceRequest.ProtoReflect.Descriptor instead.
func (*DescribeServiceRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{3}
}

type DescribeServiceResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServiceId          string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	AvailableTemplates []string               `protobuf:"bytes,3,rep,name=available_templates,json=availableTemplates,proto3" json:"available_templates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DescribeServiceResponse) Reset() {
	*x = DescribeServiceResponse{}
	mi := &file_template_v1_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceResponse) ProtoMessage() {}

func (x *DescribeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceResponse.ProtoReflect.Descriptor instead.
func (*DescribeServiceResponse) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DescribeServiceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeServiceResponse) GetAvailableTemplates() []string {
	if x != nil {
		return x.AvailableTemplates
	}
	return nil
}

var File_template_v1_template_proto protoreflect.FileDescriptor

const file_template_v1_template_proto_rawDesc = "" +
	"\n" +
	"\x1atemplate/v1/template.proto\x12\x13paigram.template.v1\"\x98\x01\n" +
	"\x16RenderAndUploadRequest\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\x12<\n" +
	"\aoptions\x18\x03 \x01(\v2\".paigram.template.v1.RenderOptionsR\aoptions\"\xa7\x01\n" +
	"\rRenderOptions\x12%\n" +
	"\x0eviewport_width\x18\x01 \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\x02 \x01(\x05R\x0eviewportHeight\x12.\n" +
	"\x13device_scale_factor\x18\x03 \x01(\x02R\x11deviceScaleFactor\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\x91\x01\n" +
	"\x17RenderAndUploadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\"\x18\n" +
	"\x16DescribeServiceRequest\"\x83\x01\n" +
	"\x17DescribeServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12/\n" +
	"\x13available_templates\x18\x03 \x03(\tR\x12availableTemplates2\xed\x01\n" +
	"\x0fTemplateService\x12l\n" +
	"\x0fRenderAndUpload\x12+.paigram.template.v1.RenderAndUploadRequest\x1a,.paigram.template.v1.RenderAndUploadResponse\x12l\n" +
	"\x0fDescribeService\x12+.paigram.template.v1.DescribeServiceRequest\x1a,.paigram.template.v1.DescribeServiceResponseB?Z=github.com/PaiGramTeam/proto-contracts/template/v1;templatev1b\x06proto3"

var (
	file_template_v1_template_proto_rawDescOnce sync.Once
	file_template_v1_template_proto_rawDescData []byte
)

func file_template_v1_template_proto_rawDescGZIP() []byte {
	file_template_v1_template_proto_rawDescOnce.Do(func() {
		file_template_v1_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_v1_template_proto_rawDesc), len(file_template_v1_template_proto_rawDesc)))
	})
	return file_template_v1_template_proto_rawDescData
}

var file_template_v1_template_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_template_v1_template_proto_goTypes = []any{
	(*RenderAndUploadRequest)(nil),  // 0: paigram.template.v1.RenderAndUploadRequest
	(*RenderOptions)(nil),           // 1: paigram.template.v1.RenderOptions
	(*RenderAndUploadResponse)(nil), // 2: paigram.template.v1.RenderAndUploadResponse
	(*DescribeServiceRequest)(nil),  // 3: paigram.template.v1.DescribeServiceRequest
	(*DescribeServiceResponse)(nil), // 4: paigram.template.v1.DescribeServiceResponse
}
var file_template_v1_template_proto_depIdxs = []int32{
	1, // 0: paigram.template.v1.RenderAndUploadRequest.options:type_name -> paigram.template.v1.RenderOptions
	0, // 1: paigram.template.v1.TemplateService.RenderAndUpload:input_type -> paigram.template.v1.RenderAndUploadRequest
	3, // 2: paigram.template.v1.TemplateService.DescribeService:input_type -> paigram.template.v1.DescribeServiceRequest
	2, // 3: paigram.template.v1.TemplateService.RenderAndUpload:output_type -> paigram.template.v1.RenderAndUploadResponse
	4, // 4: paigram.template.v1.TemplateService.DescribeService:output_type -> paigram.template.v1.DescribeServiceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_template_v1_template_proto_init() }
func file_template_v1_template_proto_init() {
	if File_template_v1_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_v1_template_proto_rawDesc), len(file_template_v1_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_v1_template_proto_goTypes,
		DependencyIndexes: file_template_v1_template_proto_depIdxs,
		MessageInfos:      file_template_v1_template_proto_msgTypes,
	}.Build()
	File_template_v1_template_proto = out.File
	file_template_v1_template_proto_goTypes = nil
	file_template_v1_template_proto_depIdxs = nil
}
