// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bot/v1/bot_service.proto

package botv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *MessageContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_bot_v1_bot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_bot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_bot_v1_bot_service_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetContext() *MessageContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*BotResponse         `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_bot_v1_bot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_bot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_bot_v1_bot_service_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetResponses() []*BotResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type DescribeServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeServiceRequest) Reset() {
	*x = DescribeServiceRequest{}
	mi := &file_bot_v1_bot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceRequest) ProtoMessage() {}

func (x *DescribeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_bot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceRequest.ProtoReflect.Descriptor instead.
func (*DescribeServiceRequest) Descriptor() ([]byte, []int) {
	return file_bot_v1_bot_service_proto_rawDescGZIP(), []int{2}
}

type DescribeServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务的稳定标识（如 "paigram-genshin"），用于路由表与日志。
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// 实现版本，建议 SemVer。
	Version       string                `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Handlers      []*HandlerDeclaration `protobuf:"bytes,3,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeServiceResponse) Reset() {
	*x = DescribeServiceResponse{}
	mi := &file_bot_v1_bot_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeServiceResponse) ProtoMessage() {}

func (x *DescribeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_bot_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeServiceResponse.ProtoReflect.Descriptor instead.
func (*DescribeServiceResponse) Descriptor() ([]byte, []int) {
	return file_bot_v1_bot_service_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DescribeServiceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeServiceResponse) GetHandlers() []*HandlerDeclaration {
	if x != nil {
		return x.Handlers
	}
	return nil
}

var File_bot_v1_bot_service_proto protoreflect.FileDescriptor

const file_bot_v1_bot_service_proto_rawDesc = "" +
	"\n" +
	"\x18bot/v1/bot_service.proto\x12\x0epaigram.bot.v1\x1a\x15bot/v1/messages.proto\x1a\x14bot/v1/handler.proto\"K\n" +
	"\x0fDispatchRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.paigram.bot.v1.MessageContextR\acontext\"M\n" +
	"\x10DispatchResponse\x129\n" +
	"\tresponses\x18\x01 \x03(\v2\x1b.paigram.bot.v1.BotResponseR\tresponses\"\x18\n" +
	"\x16DescribeServiceRequest\"\x92\x01\n" +
	"\x17DescribeServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12>\n" +
	"\bhandlers\x18\x03 \x03(\v2\".paigram.bot.v1.HandlerDeclarationR\bhandlers2\xbf\x01\n" +
	"\n" +
	"BotService\x12M\n" +
	"\bDispatch\x12\x1f.paigram.bot.v1.DispatchRequest\x1a .paigram.bot.v1.DispatchResponse\x12b\n" +
	"\x0fDescribeService\x12&.paigram.bot.v1.DescribeServiceRequest\x1a'.paigram.bot.v1.DescribeServiceResponseB5Z3github.com/PaiGramTeam/proto-contracts/bot/v1;botv1b\x06proto3"

var (
	file_bot_v1_bot_service_proto_rawDescOnce sync.Once
	file_bot_v1_bot_service_proto_rawDescData []byte
)

func file_bot_v1_bot_service_proto_rawDescGZIP() []byte {
	file_bot_v1_bot_service_proto_rawDescOnce.Do(func() {
		file_bot_v1_bot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_v1_bot_service_proto_rawDesc), len(file_bot_v1_bot_service_proto_rawDesc)))
	})
	return file_bot_v1_bot_service_proto_rawDescData
}

var file_bot_v1_bot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bot_v1_bot_service_proto_goTypes = []any{
	(*DispatchRequest)(nil),         // 0: paigram.bot.v1.DispatchRequest
	(*DispatchResponse)(nil),        // 1: paigram.bot.v1.DispatchResponse
	(*DescribeServiceRequest)(nil),  // 2: paigram.bot.v1.DescribeServiceRequest
	(*DescribeServiceResponse)(nil), // 3: paigram.bot.v1.DescribeServiceResponse
	(*MessageContext)(nil),          // 4: paigram.bot.v1.MessageContext
	(*BotResponse)(nil),             // 5: paigram.bot.v1.BotResponse
	(*HandlerDeclaration)(nil),      // 6: paigram.bot.v1.HandlerDeclaration
}
var file_bot_v1_bot_service_proto_depIdxs = []int32{
	4, // 0: paigram.bot.v1.DispatchRequest.context:type_name -> paigram.bot.v1.MessageContext
	5, // 1: paigram.bot.v1.DispatchResponse.responses:type_name -> paigram.bot.v1.BotResponse
	6, // 2: paigram.bot.v1.DescribeServiceResponse.handlers:type_name -> paigram.bot.v1.HandlerDeclaration
	0, // 3: paigram.bot.v1.BotService.Dispatch:input_type -> paigram.bot.v1.DispatchRequest
	2, // 4: paigram.bot.v1.BotService.DescribeService:input_type -> paigram.bot.v1.DescribeServiceRequest
	1, // 5: paigram.bot.v1.BotService.Dispatch:output_type -> paigram.bot.v1.DispatchResponse
	3, // 6: paigram.bot.v1.BotService.DescribeService:output_type -> paigram.bot.v1.DescribeServiceResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bot_v1_bot_service_proto_init() }
func file_bot_v1_bot_service_proto_init() {
	if File_bot_v1_bot_service_proto != nil {
		return
	}
	file_bot_v1_messages_proto_init()
	file_bot_v1_handler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_v1_bot_service_proto_rawDesc), len(file_bot_v1_bot_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_v1_bot_service_proto_goTypes,
		DependencyIndexes: file_bot_v1_bot_service_proto_depIdxs,
		MessageInfos:      file_bot_v1_bot_service_proto_msgTypes,
	}.Build()
	File_bot_v1_bot_service_proto = out.File
	file_bot_v1_bot_service_proto_goTypes = nil
	file_bot_v1_bot_service_proto_depIdxs = nil
}
