// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bot/v1/handler.proto

package botv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerVisibility int32

const (
	HandlerVisibility_HANDLER_VISIBILITY_UNSPECIFIED HandlerVisibility = 0
	// 进 /help 列表，公开可见。
	HandlerVisibility_HANDLER_VISIBILITY_PUBLIC HandlerVisibility = 1
	// 不进 /help 但可调用。
	HandlerVisibility_HANDLER_VISIBILITY_HIDDEN HandlerVisibility = 2
)

// Enum value maps for HandlerVisibility.
var (
	HandlerVisibility_name = map[int32]string{
		0: "HANDLER_VISIBILITY_UNSPECIFIED",
		1: "HANDLER_VISIBILITY_PUBLIC",
		2: "HANDLER_VISIBILITY_HIDDEN",
	}
	HandlerVisibility_value = map[string]int32{
		"HANDLER_VISIBILITY_UNSPECIFIED": 0,
		"HANDLER_VISIBILITY_PUBLIC":      1,
		"HANDLER_VISIBILITY_HIDDEN":      2,
	}
)

func (x HandlerVisibility) Enum() *HandlerVisibility {
	p := new(HandlerVisibility)
	*p = x
	return p
}

func (x HandlerVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandlerVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_v1_handler_proto_enumTypes[0].Descriptor()
}

func (HandlerVisibility) Type() protoreflect.EnumType {
	return &file_bot_v1_handler_proto_enumTypes[0]
}

func (x HandlerVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandlerVisibility.Descriptor instead.
func (HandlerVisibility) EnumDescriptor() ([]byte, []int) {
	return file_bot_v1_handler_proto_rawDescGZIP(), []int{0}
}

// HandlerDeclaration 是 game-service 在 DescribeService 中暴露的单个命令元数据。
type HandlerDeclaration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 命令名，去掉斜杠前缀（"sign"、"help"）。
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// 人类可读描述，作为 /help 一行使用。
	Description   string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    HandlerVisibility `protobuf:"varint,3,opt,name=visibility,proto3,enum=paigram.bot.v1.HandlerVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerDeclaration) Reset() {
	*x = HandlerDeclaration{}
	mi := &file_bot_v1_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerDeclaration) ProtoMessage() {}

func (x *HandlerDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerDeclaration.ProtoReflect.Descriptor instead.
func (*HandlerDeclaration) Descriptor() ([]byte, []int) {
	return file_bot_v1_handler_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerDeclaration) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HandlerDeclaration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HandlerDeclaration) GetVisibility() HandlerVisibility {
	if x != nil {
		return x.Visibility
	}
	return HandlerVisibility_HANDLER_VISIBILITY_UNSPECIFIED
}

var File_bot_v1_handler_proto protoreflect.FileDescriptor

const file_bot_v1_handler_proto_rawDesc = "" +
	"\n" +
	"\x14bot/v1/handler.proto\x12\x0epaigram.bot.v1\"\x93\x01\n" +
	"\x12HandlerDeclaration\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12A\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2!.paigram.bot.v1.HandlerVisibilityR\n" +
	"visibility*u\n" +
	"\x11HandlerVisibility\x12\"\n" +
	"\x1eHANDLER_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19HANDLER_VISIBILITY_PUBLIC\x10\x01\x12\x1d\n" +
	"\x19HANDLER_VISIBILITY_HIDDEN\x10\x02B5Z3github.com/PaiGramTeam/proto-contracts/bot/v1;botv1b\x06proto3"

var (
	file_bot_v1_handler_proto_rawDescOnce sync.Once
	file_bot_v1_handler_proto_rawDescData []byte
)

func file_bot_v1_handler_proto_rawDescGZIP() []byte {
	file_bot_v1_handler_proto_rawDescOnce.Do(func() {
		file_bot_v1_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_v1_handler_proto_rawDesc), len(file_bot_v1_handler_proto_rawDesc)))
	})
	return file_bot_v1_handler_proto_rawDescData
}

var file_bot_v1_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bot_v1_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bot_v1_handler_proto_goTypes = []any{
	(HandlerVisibility)(0),     // 0: paigram.bot.v1.HandlerVisibility
	(*HandlerDeclaration)(nil), // 1: paigram.bot.v1.HandlerDeclaration
}
var file_bot_v1_handler_proto_depIdxs = []int32{
	0, // 0: paigram.bot.v1.HandlerDeclaration.visibility:type_name -> paigram.bot.v1.HandlerVisibility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bot_v1_handler_proto_init() }
func file_bot_v1_handler_proto_init() {
	if File_bot_v1_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_v1_handler_proto_rawDesc), len(file_bot_v1_handler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bot_v1_handler_proto_goTypes,
		DependencyIndexes: file_bot_v1_handler_proto_depIdxs,
		EnumInfos:         file_bot_v1_handler_proto_enumTypes,
		MessageInfos:      file_bot_v1_handler_proto_msgTypes,
	}.Build()
	File_bot_v1_handler_proto = out.File
	file_bot_v1_handler_proto_goTypes = nil
	file_bot_v1_handler_proto_depIdxs = nil
}
