// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bot/v1/messages.proto

package botv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseMode int32

const (
	ParseMode_PARSE_MODE_UNSPECIFIED ParseMode = 0
	ParseMode_PARSE_MODE_MARKDOWN_V2 ParseMode = 1
	ParseMode_PARSE_MODE_HTML        ParseMode = 2
	ParseMode_PARSE_MODE_PLAIN       ParseMode = 3
)

// Enum value maps for ParseMode.
var (
	ParseMode_name = map[int32]string{
		0: "PARSE_MODE_UNSPECIFIED",
		1: "PARSE_MODE_MARKDOWN_V2",
		2: "PARSE_MODE_HTML",
		3: "PARSE_MODE_PLAIN",
	}
	ParseMode_value = map[string]int32{
		"PARSE_MODE_UNSPECIFIED": 0,
		"PARSE_MODE_MARKDOWN_V2": 1,
		"PARSE_MODE_HTML":        2,
		"PARSE_MODE_PLAIN":       3,
	}
)

func (x ParseMode) Enum() *ParseMode {
	p := new(ParseMode)
	*p = x
	return p
}

func (x ParseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_v1_messages_proto_enumTypes[0].Descriptor()
}

func (ParseMode) Type() protoreflect.EnumType {
	return &file_bot_v1_messages_proto_enumTypes[0]
}

func (x ParseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseMode.Descriptor instead.
func (ParseMode) EnumDescriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{0}
}

// UserIdentity 标识一个平台用户的稳定身份。
type UserIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 平台原生用户 id（telegram 是 int64 字符串化、matrix 是 mxid 等）。
	PlatformUserId string `protobuf:"bytes,1,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	DisplayName    string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// BCP-47 语言标签，可空。
	LanguageCode  string `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_bot_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdentity) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *UserIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserIdentity) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

// MessageContext 是 game-service 处理一次入站消息所需的全部跨平台上下文。
type MessageContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 平台标识符（"telegram" / "matrix" / "discord" ...）。
	Platform string        `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	User     *UserIdentity `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// 平台原生 chat/room id 字符串化。
	ChatId string `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// 消息原文。
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// 解析后命令名（"sign" / "start" ...），无命令时为空。
	Command string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	// 解析后参数列表，按空白拆分。
	Args []string `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	// 平台扩展槽。1:1:1 阶段仅 telegram 会被填充。
	// next-tag: 101
	//
	// Types that are valid to be assigned to PlatformExtra:
	//
	//	*MessageContext_Telegram
	PlatformExtra isMessageContext_PlatformExtra `protobuf_oneof:"platform_extra"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContext) Reset() {
	*x = MessageContext{}
	mi := &file_bot_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContext) ProtoMessage() {}

func (x *MessageContext) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContext.ProtoReflect.Descriptor instead.
func (*MessageContext) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageContext) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *MessageContext) GetUser() *UserIdentity {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MessageContext) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MessageContext) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContext) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MessageContext) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *MessageContext) GetPlatformExtra() isMessageContext_PlatformExtra {
	if x != nil {
		return x.PlatformExtra
	}
	return nil
}

func (x *MessageContext) GetTelegram() *TelegramExtra {
	if x != nil {
		if x, ok := x.PlatformExtra.(*MessageContext_Telegram); ok {
			return x.Telegram
		}
	}
	return nil
}

type isMessageContext_PlatformExtra interface {
	isMessageContext_PlatformExtra()
}

type MessageContext_Telegram struct {
	Telegram *TelegramExtra `protobuf:"bytes,100,opt,name=telegram,proto3,oneof"`
}

func (*MessageContext_Telegram) isMessageContext_PlatformExtra() {}

// TelegramExtra 携带不应污染通用 MessageContext 的 telegram-specific 字段。
type TelegramExtra struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IsGroup        bool                   `protobuf:"varint,2,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	TelegramUserId int64                  `protobuf:"varint,3,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	TelegramChatId int64                  `protobuf:"varint,4,opt,name=telegram_chat_id,json=telegramChatId,proto3" json:"telegram_chat_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelegramExtra) Reset() {
	*x = TelegramExtra{}
	mi := &file_bot_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramExtra) ProtoMessage() {}

func (x *TelegramExtra) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramExtra.ProtoReflect.Descriptor instead.
func (*TelegramExtra) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramExtra) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *TelegramExtra) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *TelegramExtra) GetTelegramUserId() int64 {
	if x != nil {
		return x.TelegramUserId
	}
	return 0
}

func (x *TelegramExtra) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

// BotResponse 是 game-service 单次回复的统一信封。
type BotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// next-tag: 3
	//
	// Types that are valid to be assigned to Body:
	//
	//	*BotResponse_Text
	//	*BotResponse_Photo
	Body          isBotResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotResponse) Reset() {
	*x = BotResponse{}
	mi := &file_bot_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotResponse) ProtoMessage() {}

func (x *BotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotResponse.ProtoReflect.Descriptor instead.
func (*BotResponse) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BotResponse) GetBody() isBotResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BotResponse) GetText() *TextResponse {
	if x != nil {
		if x, ok := x.Body.(*BotResponse_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *BotResponse) GetPhoto() *PhotoResponse {
	if x != nil {
		if x, ok := x.Body.(*BotResponse_Photo); ok {
			return x.Photo
		}
	}
	return nil
}

type isBotResponse_Body interface {
	isBotResponse_Body()
}

type BotResponse_Text struct {
	Text *TextResponse `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type BotResponse_Photo struct {
	Photo *PhotoResponse `protobuf:"bytes,2,opt,name=photo,proto3,oneof"`
}

func (*BotResponse_Text) isBotResponse_Body() {}

func (*BotResponse_Photo) isBotResponse_Body() {}

type TextResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Content               string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ParseMode             ParseMode              `protobuf:"varint,2,opt,name=parse_mode,json=parseMode,proto3,enum=paigram.bot.v1.ParseMode" json:"parse_mode,omitempty"`
	DisableWebPagePreview bool                   `protobuf:"varint,3,opt,name=disable_web_page_preview,json=disableWebPagePreview,proto3" json:"disable_web_page_preview,omitempty"`
	// 字段 4..9 保留作未来扁平字段；10+ 留给复合选项。
	Reply         *ReplyOptions `protobuf:"bytes,10,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_bot_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TextResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextResponse) GetParseMode() ParseMode {
	if x != nil {
		return x.ParseMode
	}
	return ParseMode_PARSE_MODE_UNSPECIFIED
}

func (x *TextResponse) GetDisableWebPagePreview() bool {
	if x != nil {
		return x.DisableWebPagePreview
	}
	return false
}

func (x *TextResponse) GetReply() *ReplyOptions {
	if x != nil {
		return x.Reply
	}
	return nil
}

type PhotoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 必填：minio URL 或 Telegram file_id。永不携带 bytes（spec §3 决策）。
	PhotoUrl         string    `protobuf:"bytes,1,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Caption          string    `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	CaptionParseMode ParseMode `protobuf:"varint,3,opt,name=caption_parse_mode,json=captionParseMode,proto3,enum=paigram.bot.v1.ParseMode" json:"caption_parse_mode,omitempty"`
	// 字段 4..9 保留作未来扁平字段；10+ 留给复合选项。
	Reply         *ReplyOptions `protobuf:"bytes,10,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoResponse) Reset() {
	*x = PhotoResponse{}
	mi := &file_bot_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoResponse) ProtoMessage() {}

func (x *PhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoResponse.ProtoReflect.Descriptor instead.
func (*PhotoResponse) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PhotoResponse) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *PhotoResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *PhotoResponse) GetCaptionParseMode() ParseMode {
	if x != nil {
		return x.CaptionParseMode
	}
	return ParseMode_PARSE_MODE_UNSPECIFIED
}

func (x *PhotoResponse) GetReply() *ReplyOptions {
	if x != nil {
		return x.Reply
	}
	return nil
}

type ReplyOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 表示不 reply。
	ReplyToMessageId int64 `protobuf:"varint,1,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyOptions) Reset() {
	*x = ReplyOptions{}
	mi := &file_bot_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyOptions) ProtoMessage() {}

func (x *ReplyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bot_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyOptions.ProtoReflect.Descriptor instead.
func (*ReplyOptions) Descriptor() ([]byte, []int) {
	return file_bot_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyOptions) GetReplyToMessageId() int64 {
	if x != nil {
		return x.ReplyToMessageId
	}
	return 0
}

var File_bot_v1_messages_proto protoreflect.FileDescriptor

const file_bot_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x15bot/v1/messages.proto\x12\x0epaigram.bot.v1\"\x80\x01\n" +
	"\fUserIdentity\x12(\n" +
	"\x10platform_user_id\x18\x01 \x01(\tR\x0eplatformUserId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\"\x88\x02\n" +
	"\x0eMessageContext\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x120\n" +
	"\x04user\x18\x02 \x01(\v2\x1c.paigram.bot.v1.UserIdentityR\x04user\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12;\n" +
	"\btelegram\x18d \x01(\v2\x1d.paigram.bot.v1.TelegramExtraH\x00R\btelegramB\x10\n" +
	"\x0eplatform_extra\"\x9d\x01\n" +
	"\rTelegramExtra\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x19\n" +
	"\bis_group\x18\x02 \x01(\bR\aisGroup\x12(\n" +
	"\x10telegram_user_id\x18\x03 \x01(\x03R\x0etelegramUserId\x12(\n" +
	"\x10telegram_chat_id\x18\x04 \x01(\x03R\x0etelegramChatId\"\x80\x01\n" +
	"\vBotResponse\x122\n" +
	"\x04text\x18\x01 \x01(\v2\x1c.paigram.bot.v1.TextResponseH\x00R\x04text\x125\n" +
	"\x05photo\x18\x02 \x01(\v2\x1d.paigram.bot.v1.PhotoResponseH\x00R\x05photoB\x06\n" +
	"\x04body\"\xcf\x01\n" +
	"\fTextResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x128\n" +
	"\n" +
	"parse_mode\x18\x02 \x01(\x0e2\x19.paigram.bot.v1.ParseModeR\tparseMode\x127\n" +
	"\x18disable_web_page_preview\x18\x03 \x01(\bR\x15disableWebPagePreview\x122\n" +
	"\x05reply\x18\n" +
	" \x01(\v2\x1c.paigram.bot.v1.ReplyOptionsR\x05reply\"\xc3\x01\n" +
	"\rPhotoResponse\x12\x1b\n" +
	"\tphoto_url\x18\x01 \x01(\tR\bphotoUrl\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12G\n" +
	"\x12caption_parse_mode\x18\x03 \x01(\x0e2\x19.paigram.bot.v1.ParseModeR\x10captionParseMode\x122\n" +
	"\x05reply\x18\n" +
	" \x01(\v2\x1c.paigram.bot.v1.ReplyOptionsR\x05reply\"=\n" +
	"\fReplyOptions\x12-\n" +
	"\x13reply_to_message_id\x18\x01 \x01(\x03R\x10replyToMessageId*n\n" +
	"\tParseMode\x12\x1a\n" +
	"\x16PARSE_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PARSE_MODE_MARKDOWN_V2\x10\x01\x12\x13\n" +
	"\x0fPARSE_MODE_HTML\x10\x02\x12\x14\n" +
	"\x10PARSE_MODE_PLAIN\x10\x03B5Z3github.com/PaiGramTeam/proto-contracts/bot/v1;botv1b\x06proto3"

var (
	file_bot_v1_messages_proto_rawDescOnce sync.Once
	file_bot_v1_messages_proto_rawDescData []byte
)

func file_bot_v1_messages_proto_rawDescGZIP() []byte {
	file_bot_v1_messages_proto_rawDescOnce.Do(func() {
		file_bot_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_v1_messages_proto_rawDesc), len(file_bot_v1_messages_proto_rawDesc)))
	})
	return file_bot_v1_messages_proto_rawDescData
}

var file_bot_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bot_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bot_v1_messages_proto_goTypes = []any{
	(ParseMode)(0),         // 0: paigram.bot.v1.ParseMode
	(*UserIdentity)(nil),   // 1: paigram.bot.v1.UserIdentity
	(*MessageContext)(nil), // 2: paigram.bot.v1.MessageContext
	(*TelegramExtra)(nil),  // 3: paigram.bot.v1.TelegramExtra
	(*BotResponse)(nil),    // 4: paigram.bot.v1.BotResponse
	(*TextResponse)(nil),   // 5: paigram.bot.v1.TextResponse
	(*PhotoResponse)(nil),  // 6: paigram.bot.v1.PhotoResponse
	(*ReplyOptions)(nil),   // 7: paigram.bot.v1.ReplyOptions
}
var file_bot_v1_messages_proto_depIdxs = []int32{
	1, // 0: paigram.bot.v1.MessageContext.user:type_name -> paigram.bot.v1.UserIdentity
	3, // 1: paigram.bot.v1.MessageContext.telegram:type_name -> paigram.bot.v1.TelegramExtra
	5, // 2: paigram.bot.v1.BotResponse.text:type_name -> paigram.bot.v1.TextResponse
	6, // 3: paigram.bot.v1.BotResponse.photo:type_name -> paigram.bot.v1.PhotoResponse
	0, // 4: paigram.bot.v1.TextResponse.parse_mode:type_name -> paigram.bot.v1.ParseMode
	7, // 5: paigram.bot.v1.TextResponse.reply:type_name -> paigram.bot.v1.ReplyOptions
	0, // 6: paigram.bot.v1.PhotoResponse.caption_parse_mode:type_name -> paigram.bot.v1.ParseMode
	7, // 7: paigram.bot.v1.PhotoResponse.reply:type_name -> paigram.bot.v1.ReplyOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_bot_v1_messages_proto_init() }
func file_bot_v1_messages_proto_init() {
	if File_bot_v1_messages_proto != nil {
		return
	}
	file_bot_v1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageContext_Telegram)(nil),
	}
	file_bot_v1_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*BotResponse_Text)(nil),
		(*BotResponse_Photo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_v1_messages_proto_rawDesc), len(file_bot_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bot_v1_messages_proto_goTypes,
		DependencyIndexes: file_bot_v1_messages_proto_depIdxs,
		EnumInfos:         file_bot_v1_messages_proto_enumTypes,
		MessageInfos:      file_bot_v1_messages_proto_msgTypes,
	}.Build()
	File_bot_v1_messages_proto = out.File
	file_bot_v1_messages_proto_goTypes = nil
	file_bot_v1_messages_proto_depIdxs = nil
}
